### ISSUE TITLE
KeyError: 'anchor_spk'

### ISSUE THREAD

**Issue by coding-dallas** [gusrud1103/LibriPhrase#3]
* Finish 2 word class
* Time check:  0.017576721443070306 hours
Step 4-1 : Extract df word class 3
94746it [00:03, 24613.79it/s]
Step 4-2 : Start making positive
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 66052.03it/s]
Step 4-3 : Start making negative
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 15.89it/s]
0it [00:00, ?it/s]
# of positive case rows =  0
# of negative case rows =  0
Traceback (most recent call last):
  File "/asr3/kesav/keywrd_file_prep/LibriPhrase/LibriPhrase_test_clean/codes/libriphrase.py", line 110, in <module>
    main(args)
  File "/asr3/kesav/keywrd_file_prep/LibriPhrase/LibriPhrase_test_clean/codes/libriphrase.py", line 95, in main
    total_df = total_df.sort_values(by=['anchor_spk', 'anchor_text', 'target', 'type', 'comparison_spk'], ascending=[True, True, True, True, True])
  File "/home/asr/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 6740, in sort_values
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/home/asr/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 6740, in <listcomp>
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/home/asr/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'anchor_spk'

I am trying to prepare libriphrase dataset from librispeech test clean. for up to 2 word class, it is working fine. when extracting 3 word class, it is throwing the above error. 

below are the parameter i passed for preparing the dataset.

python3 libriphrase.py --libripath '/asr3/kesav/keywrd_file_prep/LibriPhrase/LibriPhrase_test_clean/data/LibriSpeech_clean_wav/' --newpath '/asr3/kesav/keywrd_file_prep/LibriPhrase/LibriPhrase_test_clean/data/LibriPhrase_diffspk_all/' --wordalign '/asr3/kesav/keywrd_file_prep/LibriPhrase/LibriPhrase_test_clean/metadata/librispeech_clean_test_all_utt_with_flac.csv' --output '/asr3/kesav/keywrd_file_prep/LibriPhrase/LibriPhrase_test_clean/metadata/librispeech_clean_test_short_phrase.csv' --numpair 3 --maxspk 1611 --maxword 4 --mode 'diffspk_all'

**Comment by gusrud1103** [comment]
Hi, it seems you should use librispeech train-other-500h data for making LibriPhrase evalution set in principle.
If you want to use librispeech test-clean, you need to reduce maxspk since the number of speakers from test-clean is smaller than train-other-500h.

**Comment by coding-dallas** [comment]
i am not clear what the parameters  ( --numpair, --maxsp) tells
